config/routes.rb
Rails.application.routes.draw do
  draw(:admin)
  

  root to: "home#index"
  
  devise_for :users

  post "/users/:id/create_wallet", to: "users#create_wallet", as: :create_wallet
  post "/users/:id/fund_wallet", to: "users#fund_wallet", as: :fund_wallet
  post "/users/:id/transfer", to: "users#transfer", as: :transfer_wallet

  resources :follow_requests
  resources :user_tandas
  resources :transactions
  resources :tandas
  resources :analytics, only: [:index]
  
  get "/service-worker.js", to: "pwa#service_worker"
  get "/manifest.json", to: "pwa#manifest"
  get "/wallet", to: "users#wallet", as: :user_wallet
  get "/friends", to: "users#friends", as: :friends
  get "/search_users", to: "users#search", as: :search_users
  get "/:username" => "users#show", as: :user
end

app/models/user_tanda.rb
# == Schema Information
#
# Table name: user_tandas
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tanda_id   :integer
#  user_id    :integer
#
class UserTanda < ApplicationRecord
  belongs_to :user
  belongs_to :tanda
  has_many :transactions

  def tanda_name
    tanda.name
  end

  def trackable_type
    "UserTanda"
  end

  def trackable_id
    id
  end
end

app/controllers/user_tandas_controller.rb
class UserTandasController < ApplicationController
  before_action :set_user_tanda, only: %i[ show edit update destroy ]

  def index
    @user_tandas = UserTanda.all
  end

  def show
  end

  def new
    @user_tanda = UserTanda.new
  end

  def edit
  end

  def create
    @user_tanda = UserTanda.new(user_tanda_params)

    respond_to do |format|
      if @user_tanda.save
        format.html { redirect_to user_tanda_url(@user_tanda), notice: "User tanda was successfully created." }
        format.json { render :show, status: :created, location: @user_tanda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_tanda.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user_tanda.update(user_tanda_params)
        format.html { redirect_to user_tanda_url(@user_tanda), notice: "User tanda was successfully updated." }
        format.json { render :show, status: :ok, location: @user_tanda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_tanda.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user_tanda.destroy!

    respond_to do |format|
      format.html { redirect_to user_tandas_url, notice: "User tanda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_user_tanda
    @user_tanda = UserTanda.find(params[:id])
  end

  def user_tanda_params
    params.require(:user_tanda).permit(:goal_id, :user_id)
  end
end

app/views/user_tandas/_form.html.erb
<%= simple_form_for(@user_tanda) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :tanda_id %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_tandas/_user_tanda.html.erb
<div id="<%= dom_id user_tanda %>">
  <p>
    <strong>Goal:</strong>
    <%= user_tanda.tanda_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= user_tanda.user_id %>
  </p>

</div>

app/views/user_tandas/edit.html.erb
<h1>Editing user tanda</h1>

<%= render "form", user_tanda: @user_tanda %>

<br>

<div>
  <%= link_to "Show this user tanda", @user_tanda %> |
  <%= link_to "Back to user tandas", user_tandas_path %>
</div>

app/views/user_tandas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User tandas</h1>

<div id="user_tandas">
  <% @user_tandas.each do |user_tanda| %>
    <%= render user_tanda %>
    <p>
      <%= link_to "Show this user tanda", user_tanda %>
    </p>
  <% end %>
</div>

<%= link_to "New user tanda", new_user_tanda_path %>

app/views/user_tandas/new.html.erb
<h1>New user tanda</h1>

<%= render "form", user_tanda: @user_tanda %>

<br>

<div>
  <%= link_to "Back to user tandas", user_tandas_path %>
</div>

app/views/user_tandas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_tanda %>

<div>
  <%= link_to "Edit this user tanda", edit_user_tanda_path(@user_tanda) %> |
  <%= link_to "Back to user tandas", user_tandas_path %>

  <%= button_to "Destroy this user tanda", @user_tanda, method: :delete %>
</div>